---
- hosts: filebeat_docker_logs_jenkins_hosts

  vars_files:
  - vars.yml

  roles:
  - role: check_mounts
    tags: check_mounts

  - role: filebeat_docker_logs_jenkins
    tags: filebeat_docker_logs_jenkins
