---
- name: Deletes existing Jenkins container.
  tags: jenkins_delete_container
  docker:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    docker_api_version: "{{ docker_api_version }}"
    state: absent

- name: Deletes existing Jenkins data container.
  tags: jenkins_delete_data_container
  docker:
    name: "{{ jenkins_data_container_name }}"
    image: "{{ jenkins_image }}"
    docker_api_version: "{{ docker_api_version }}"
    state: absent

- name: Creates the Jenkins directories.
  tags: jenkins_dirs
  file: path="{{ app_dir }}/{{ item }}" state=directory mode=0755
  ignore_errors: yes
  with_items:
  - "{{ jenkins_data_dir }}"

- name: Creates the Jenkins data container.
  tags: jenkins_create_data_container
  docker:
    name: "{{ jenkins_data_container_name }}"
    image: "{{ jenkins_image }}"
    state: started
    docker_api_version: "{{ docker_api_version }}"
    command: "bash -c 'chown -R jenkins:jenkins /var/jenkins_home'"
    volumes:
    - "/appl/{{ jenkins_data_dir }}:/var/jenkins_home"

- name: Creates the Jenkins docker container.
  docker:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    state: restarted
    restart_policy: always
    docker_api_version: "{{ docker_api_version }}"
    volumes_from: "{{ jenkins_data_container_name }}"
    links:
    - "{{ mysql_container_name }}:db"
    - "{{ sonar_server_container_name }}:sonar"
    env:
      JENKINS_OPTS: "--prefix=/jenkins"
